on:
  push:
    branches:
      - 'feature/**'
jobs:
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destionation_branch: "development"
          title: "Merge Feature into Development"
        # run: gh pr create -B development -H 'feature/**' --title 'Merge Feature into Development' --body 'Created automatic Pull Request by Github action.'
        env:
            GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
            GH_TOKEN: ${{ secrets.GIT_TOKEN }}