on:
  push:
    branches:
      - feature/*
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: diillson/auto-pull-request@latest
        with:
          destination_branch: "development"