on:
  push:
    branches:
      - 'feature/**'
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to develop
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: feature
          base_branch: develop
          labels: hotfix,develop
          assignees: vncsgonca23
          reviewers: vncsgonca23