on:
  push:
    branches:
      - feature/*
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "development"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "PR feature to Development"